//Ported to JSxCAD from https://www.thingiverse.com/thing:16627/files by @BarbourSmith

// Parametric Pulley with multiple belt profiles
// by droftarts January 2012

// Based on pulleys by:
// http://www.thingiverse.com/thing:11256 by me!
// https://github.com/prusajr/PrusaMendel by Josef Prusa
// http://www.thingiverse.com/thing:3104 by GilesBathgate
// http://www.thingiverse.com/thing:2079 by nophead

// dxf tooth data from http://oem.cadregister.com/asp/PPOW_Entry.asp?company=915217&elementID=07807803/METRIC/URETH/WV0025/F
// pulley diameter checked and modeled from data at http://www.sdp-si.com/D265/HTML/D265T016.html

// tune-able constants

//  ********************************
//  ** Scaling tooth for good fit **
//  ********************************
/*  To improve fit of belt to pulley, set the following constant. Decrease or increase by 0.1mm at a time. We are modelling the *BELT* tooth here, not the tooth on the pulley. Increasing the number will *decrease* the pulley tooth size. Increasing the tooth width will also scale proportionately the tooth depth, to maintain the shape of the tooth, and increase how far into the pulley the tooth is indented. Can be negative */

const additionalToothWidth = 0.2; //mm

//  If you need more tooth depth than this provides, adjust the following constant. However, this will cause the shape of the tooth to change.

const additionalToothDepth = 0; //mm

// Functions

const ToothSpaceingCurvefit = (teeth, b, c, d) => {
  return ((c * Math.pow(teeth, d)) / (b + Math.pow(teeth, d))) * teeth;
};

const ToothSpacing = (teeth, tooth_pitch, pitch_line_offset) =>
  2 * ((teeth * tooth_pitch) / (3.14159265 * 2) - pitch_line_offset);

const ToothProfileToFace = (...points) =>
  Shape.fromOpenPath(points).loop().fill();

export const MXL = {
  profile: ToothProfileToFace(
    [-0.660421, -0.5, 0],
    [-0.660421, 0, 0],
    [-0.621898, 0.006033, 0],
    [-0.587714, 0.023037, 0],
    [-0.560056, 0.049424, 0],
    [-0.541182, 0.083609, 0],
    [-0.417357, 0.424392, 0],
    [-0.398413, 0.458752, 0],
    [-0.370649, 0.48514, 0],
    [-0.336324, 0.502074, 0],
    [-0.297744, 0.508035, 0],
    [0.297744, 0.508035, 0],
    [0.336268, 0.502074, 0],
    [0.370452, 0.48514, 0],
    [0.39811, 0.458752, 0],
    [0.416983, 0.424392, 0],
    [0.540808, 0.083609, 0],
    [0.559752, 0.049424, 0],
    [0.587516, 0.023037, 0],
    [0.621841, 0.006033, 0],
    [0.660421, 0, 0],
    [0.660421, -0.5, 0]
  )
    .md('MXL profile')
    .gridView(),
  diameter: (teeth) => ToothSpacing(teeth, 2.032, 0.254),
  toothDepth: 0.508,
  toothWidth: 1.321,
};

export const DP40 = {
  profile: ToothProfileToFace(
    [-0.612775, -0.5, 0],
    [-0.612775, 0, 0],
    [-0.574719, 0.010187, 0],
    [-0.546453, 0.0381, 0],
    [-0.355953, 0.3683, 0],
    [-0.327604, 0.405408, 0],
    [-0.291086, 0.433388, 0],
    [-0.248548, 0.451049, 0],
    [-0.202142, 0.4572, 0],
    [0.202494, 0.4572, 0],
    [0.248653, 0.451049, 0],
    [0.291042, 0.433388, 0],
    [0.327609, 0.405408, 0],
    [0.356306, 0.3683, 0],
    [0.546806, 0.0381, 0],
    [0.574499, 0.010187, 0],
    [0.612775, 0, 0],
    [0.612775, -0.5, 0]
  )
    .md('DP40 profile')
    .gridView(),
  diameter: (teeth) => ToothSpacing(teeth, 2.07264, 0.1778),
  toothDepth: 0.457,
  toothWidth: 1.226,
};

export const XL = {
  profile: ToothProfileToFace(
    [-1.525411, -1, 0],
    [-1.525411, 0, 0],
    [-1.41777, 0.015495, 0],
    [-1.320712, 0.059664, 0],
    [-1.239661, 0.129034, 0],
    [-1.180042, 0.220133, 0],
    [-0.793044, 1.050219, 0],
    [-0.733574, 1.141021, 0],
    [-0.652507, 1.210425, 0],
    [-0.555366, 1.254759, 0],
    [-0.447675, 1.270353, 0],
    [0.447675, 1.270353, 0],
    [0.555366, 1.254759, 0],
    [0.652507, 1.210425, 0],
    [0.733574, 1.141021, 0],
    [0.793044, 1.050219, 0],
    [1.180042, 0.220133, 0],
    [1.239711, 0.129034, 0],
    [1.320844, 0.059664, 0],
    [1.417919, 0.015495, 0],
    [1.525411, 0, 0],
    [1.525411, -1, 0]
  )
    .md('XL profile')
    .gridView(),
  diameter: (teeth) => ToothSpacing(teeth, 5.08, 0.254),
  toothDepth: 1.27,
  toothWidth: 3.051,
};

export const H = {
  profile: ToothProfileToFace(
    [-2.6797, -1, 0],
    [-2.6797, 0, 0],
    [-2.600907, 0.006138, 0],
    [-2.525342, 0.024024, 0],
    [-2.45412, 0.052881, 0],
    [-2.388351, 0.091909, 0],
    [-2.329145, 0.140328, 0],
    [-2.277614, 0.197358, 0],
    [-2.234875, 0.262205, 0],
    [-2.202032, 0.334091, 0],
    [-1.75224, 1.57093, 0],
    [-1.719538, 1.642815, 0],
    [-1.676883, 1.707663, 0],
    [-1.62542, 1.764693, 0],
    [-1.566256, 1.813112, 0],
    [-1.500512, 1.85214, 0],
    [-1.4293, 1.880997, 0],
    [-1.353742, 1.898883, 0],
    [-1.274949, 1.905021, 0],
    [1.275281, 1.905021, 0],
    [1.354056, 1.898883, 0],
    [1.429576, 1.880997, 0],
    [1.500731, 1.85214, 0],
    [1.566411, 1.813112, 0],
    [1.625508, 1.764693, 0],
    [1.676919, 1.707663, 0],
    [1.719531, 1.642815, 0],
    [1.752233, 1.57093, 0],
    [2.20273, 0.334091, 0],
    [2.235433, 0.262205, 0],
    [2.278045, 0.197358, 0],
    [2.329455, 0.140328, 0],
    [2.388553, 0.091909, 0],
    [2.454233, 0.052881, 0],
    [2.525384, 0.024024, 0],
    [2.600904, 0.006138, 0],
    [2.6797, 0, 0],
    [2.6797, -1, 0]
  )
    .md('H profile')
    .gridView(),
  diameter: (teeth) => ToothSpacing(teeth, 9.525, 0.381),
  toothDepth: 1.905,
  toothWidth: 5.359,
};

export const T2_5 = {
  profile: ToothProfileToFace(
    [-0.839258, -0.5, 0],
    [-0.839258, 0, 0],
    [-0.770246, 0.021652, 0],
    [-0.726369, 0.079022, 0],
    [-0.529167, 0.620889, 0],
    [-0.485025, 0.67826, 0],
    [-0.416278, 0.699911, 0],
    [0.416278, 0.699911, 0],
    [0.484849, 0.67826, 0],
    [0.528814, 0.620889, 0],
    [0.726369, 0.079022, 0],
    [0.770114, 0.021652, 0],
    [0.839258, 0, 0],
    [0.839258, -0.5, 0]
  )
    .md('T2_5 profile')
    .gridView(),
  diameter: (teeth) => ToothSpaceingCurvefit(teeth, 0.7467, 0.796, 1.026),
  toothDepth: 0.7,
  toothWidth: 1.678,
};

export const T5 = {
  profile: ToothProfileToFace(
    [-1.632126, -0.5, 0],
    [-1.632126, 0, 0],
    [-1.568549, 0.004939, 0],
    [-1.507539, 0.019367, 0],
    [-1.450023, 0.042686, 0],
    [-1.396912, 0.074224, 0],
    [-1.349125, 0.113379, 0],
    [-1.307581, 0.159508, 0],
    [-1.273186, 0.211991, 0],
    [-1.246868, 0.270192, 0],
    [-1.009802, 0.920362, 0],
    [-0.983414, 0.978433, 0],
    [-0.949018, 1.030788, 0],
    [-0.907524, 1.076798, 0],
    [-0.859829, 1.115847, 0],
    [-0.80682, 1.147314, 0],
    [-0.749402, 1.170562, 0],
    [-0.688471, 1.184956, 0],
    [-0.624921, 1.189895, 0],
    [0.624971, 1.189895, 0],
    [0.688622, 1.184956, 0],
    [0.749607, 1.170562, 0],
    [0.807043, 1.147314, 0],
    [0.860055, 1.115847, 0],
    [0.907754, 1.076798, 0],
    [0.949269, 1.030788, 0],
    [0.9837, 0.978433, 0],
    [1.010193, 0.920362, 0],
    [1.246907, 0.270192, 0],
    [1.273295, 0.211991, 0],
    [1.307726, 0.159508, 0],
    [1.349276, 0.113379, 0],
    [1.397039, 0.074224, 0],
    [1.450111, 0.042686, 0],
    [1.507589, 0.019367, 0],
    [1.568563, 0.004939, 0],
    [1.632126, 0, 0],
    [1.632126, -0.5, 0]
  )
    .md('T5 profile')
    .gridView(),
  diameter: (teeth) => ToothSpaceingCurvefit(teeth, 0.6523, 1.591, 1.064),
  toothDepth: 1.19,
  toothWidth: 3.264,
};

export const T10 = {
  profile: ToothProfileToFace(
    [-3.06511, -1, 0],
    [-3.06511, 0, 0],
    [-2.971998, 0.007239, 0],
    [-2.882718, 0.028344, 0],
    [-2.79859, 0.062396, 0],
    [-2.720931, 0.108479, 0],
    [-2.651061, 0.165675, 0],
    [-2.590298, 0.233065, 0],
    [-2.539962, 0.309732, 0],
    [-2.501371, 0.394759, 0],
    [-1.879071, 2.105025, 0],
    [-1.840363, 2.190052, 0],
    [-1.789939, 2.266719, 0],
    [-1.729114, 2.334109, 0],
    [-1.659202, 2.391304, 0],
    [-1.581518, 2.437387, 0],
    [-1.497376, 2.47144, 0],
    [-1.408092, 2.492545, 0],
    [-1.314979, 2.499784, 0],
    [1.314979, 2.499784, 0],
    [1.408091, 2.492545, 0],
    [1.497371, 2.47144, 0],
    [1.581499, 2.437387, 0],
    [1.659158, 2.391304, 0],
    [1.729028, 2.334109, 0],
    [1.789791, 2.266719, 0],
    [1.840127, 2.190052, 0],
    [1.878718, 2.105025, 0],
    [2.501018, 0.394759, 0],
    [2.539726, 0.309732, 0],
    [2.59015, 0.233065, 0],
    [2.650975, 0.165675, 0],
    [2.720887, 0.108479, 0],
    [2.798571, 0.062396, 0],
    [2.882713, 0.028344, 0],
    [2.971997, 0.007239, 0],
    [3.06511, 0, 0],
    [3.06511, -1, 0]
  )
    .md('T10 profile')
    .gridView(),
  diameter: (teeth) => ToothSpacing(teeth, 10, 0.93),
  toothDepth: 2.5,
  toothWidth: 6.13,
};

export const AT5 = {
  profile: ToothProfileToFace(
    [-2.134129, -0.75, 0],
    [-2.134129, 0, 0],
    [-2.058023, 0.005488, 0],
    [-1.984595, 0.021547, 0],
    [-1.914806, 0.047569, 0],
    [-1.849614, 0.082947, 0],
    [-1.789978, 0.127073, 0],
    [-1.736857, 0.179338, 0],
    [-1.691211, 0.239136, 0],
    [-1.653999, 0.305859, 0],
    [-1.349199, 0.959203, 0],
    [-1.286933, 1.054635, 0],
    [-1.201914, 1.127346, 0],
    [-1.099961, 1.173664, 0],
    [-0.986896, 1.18992, 0],
    [0.986543, 1.18992, 0],
    [1.099614, 1.173664, 0],
    [1.201605, 1.127346, 0],
    [1.286729, 1.054635, 0],
    [1.349199, 0.959203, 0],
    [1.653646, 0.305859, 0],
    [1.690859, 0.239136, 0],
    [1.73651, 0.179338, 0],
    [1.789644, 0.127073, 0],
    [1.849305, 0.082947, 0],
    [1.914539, 0.047569, 0],
    [1.984392, 0.021547, 0],
    [2.057906, 0.005488, 0],
    [2.134129, 0, 0],
    [2.134129, -0.75, 0]
  )
    .md('AT5 profile')
    .gridView(),
  diameter: (teeth) => ToothSpaceingCurvefit(teeth, 0.6523, 1.591, 1.064),
  toothDepth: 1.19,
  toothWidth: 4.268,
};

export const HTD_3mm = {
  profile: ToothProfileToFace(
    [-1.135062, -0.5, 0],
    [-1.135062, 0, 0],
    [-1.048323, 0.015484, 0],
    [-0.974284, 0.058517, 0],
    [-0.919162, 0.123974, 0],
    [-0.889176, 0.206728, 0],
    [-0.81721, 0.579614, 0],
    [-0.800806, 0.653232, 0],
    [-0.778384, 0.72416, 0],
    [-0.750244, 0.792137, 0],
    [-0.716685, 0.856903, 0],
    [-0.678005, 0.918199, 0],
    [-0.634505, 0.975764, 0],
    [-0.586483, 1.029338, 0],
    [-0.534238, 1.078662, 0],
    [-0.47807, 1.123476, 0],
    [-0.418278, 1.16352, 0],
    [-0.355162, 1.198533, 0],
    [-0.289019, 1.228257, 0],
    [-0.22015, 1.25243, 0],
    [-0.148854, 1.270793, 0],
    [-0.07543, 1.283087, 0],
    [-0.000176, 1.28905, 0],
    [0.075081, 1.283145, 0],
    [0.148515, 1.270895, 0],
    [0.219827, 1.252561, 0],
    [0.288716, 1.228406, 0],
    [0.354879, 1.19869, 0],
    [0.418018, 1.163675, 0],
    [0.477831, 1.123623, 0],
    [0.534017, 1.078795, 0],
    [0.586276, 1.029452, 0],
    [0.634307, 0.975857, 0],
    [0.677809, 0.91827, 0],
    [0.716481, 0.856953, 0],
    [0.750022, 0.792167, 0],
    [0.778133, 0.724174, 0],
    [0.800511, 0.653236, 0],
    [0.816857, 0.579614, 0],
    [0.888471, 0.206728, 0],
    [0.919014, 0.123974, 0],
    [0.974328, 0.058517, 0],
    [1.048362, 0.015484, 0],
    [1.135062, 0, 0],
    [1.135062, -0.5, 0]
  )
    .md('HTD_3mm profile')
    .gridView(),
  diameter: (teeth) => ToothSpacing(teeth, 3, 0.381),
  toothDepth: 1.289,
  toothWidth: 2.27,
};

export const HTD_5mm = {
  profile: ToothProfileToFace(
    [-1.89036, -0.75, 0],
    [-1.89036, 0, 0],
    [-1.741168, 0.02669, 0],
    [-1.61387, 0.100806, 0],
    [-1.518984, 0.21342, 0],
    [-1.467026, 0.3556, 0],
    [-1.427162, 0.960967, 0],
    [-1.398568, 1.089602, 0],
    [-1.359437, 1.213531, 0],
    [-1.310296, 1.332296, 0],
    [-1.251672, 1.445441, 0],
    [-1.184092, 1.552509, 0],
    [-1.108081, 1.653042, 0],
    [-1.024167, 1.746585, 0],
    [-0.932877, 1.832681, 0],
    [-0.834736, 1.910872, 0],
    [-0.730271, 1.980701, 0],
    [-0.62001, 2.041713, 0],
    [-0.504478, 2.09345, 0],
    [-0.384202, 2.135455, 0],
    [-0.259708, 2.167271, 0],
    [-0.131524, 2.188443, 0],
    [-0.000176, 2.198511, 0],
    [0.131296, 2.188504, 0],
    [0.259588, 2.167387, 0],
    [0.384174, 2.135616, 0],
    [0.504527, 2.093648, 0],
    [0.620123, 2.04194, 0],
    [0.730433, 1.980949, 0],
    [0.834934, 1.911132, 0],
    [0.933097, 1.832945, 0],
    [1.024398, 1.746846, 0],
    [1.108311, 1.653291, 0],
    [1.184308, 1.552736, 0],
    [1.251865, 1.445639, 0],
    [1.310455, 1.332457, 0],
    [1.359552, 1.213647, 0],
    [1.39863, 1.089664, 0],
    [1.427162, 0.960967, 0],
    [1.467026, 0.3556, 0],
    [1.518984, 0.21342, 0],
    [1.61387, 0.100806, 0],
    [1.741168, 0.02669, 0],
    [1.89036, 0, 0],
    [1.89036, -0.75, 0]
  )
    .md('HTD_5mm profile')
    .gridView(),
  diameter: (teeth) => ToothSpacing(teeth, 5, 0.5715),
  toothDepth: 2.199,
  toothWidth: 3.781,
};

export const HTD_8mm = {
  profile: ToothProfileToFace(
    [-3.301471, -1, 0],
    [-3.301471, 0, 0],
    [-3.16611, 0.012093, 0],
    [-3.038062, 0.047068, 0],
    [-2.919646, 0.10297, 0],
    [-2.813182, 0.177844, 0],
    [-2.720989, 0.269734, 0],
    [-2.645387, 0.376684, 0],
    [-2.588694, 0.496739, 0],
    [-2.553229, 0.627944, 0],
    [-2.460801, 1.470025, 0],
    [-2.411413, 1.691917, 0],
    [-2.343887, 1.905691, 0],
    [-2.259126, 2.110563, 0],
    [-2.158035, 2.30575, 0],
    [-2.041518, 2.490467, 0],
    [-1.910478, 2.66393, 0],
    [-1.76582, 2.825356, 0],
    [-1.608446, 2.973961, 0],
    [-1.439261, 3.10896, 0],
    [-1.259169, 3.22957, 0],
    [-1.069074, 3.335006, 0],
    [-0.869878, 3.424485, 0],
    [-0.662487, 3.497224, 0],
    [-0.447804, 3.552437, 0],
    [-0.226732, 3.589341, 0],
    [-0.000176, 3.607153, 0],
    [0.226511, 3.589461, 0],
    [0.447712, 3.552654, 0],
    [0.66252, 3.497516, 0],
    [0.870027, 3.424833, 0],
    [1.069329, 3.33539, 0],
    [1.259517, 3.229973, 0],
    [1.439687, 3.109367, 0],
    [1.608931, 2.974358, 0],
    [1.766344, 2.825731, 0],
    [1.911018, 2.664271, 0],
    [2.042047, 2.490765, 0],
    [2.158526, 2.305998, 0],
    [2.259547, 2.110755, 0],
    [2.344204, 1.905821, 0],
    [2.411591, 1.691983, 0],
    [2.460801, 1.470025, 0],
    [2.553229, 0.627944, 0],
    [2.588592, 0.496739, 0],
    [2.645238, 0.376684, 0],
    [2.720834, 0.269734, 0],
    [2.81305, 0.177844, 0],
    [2.919553, 0.10297, 0],
    [3.038012, 0.047068, 0],
    [3.166095, 0.012093, 0],
    [3.301471, 0, 0],
    [3.301471, -1, 0]
  )
    .md('HTD_8mm profile')
    .gridView(),
  diameter: (teeth) => ToothSpacing(teeth, 8, 0.6858),
  toothDepth: 3.607,
  toothWidth: 6.603,
};

export const GT2_2mm = {
  profile: ToothProfileToFace(
    [0.747183, -0.5, 0],
    [0.747183, 0, 0],
    [0.647876, 0.037218, 0],
    [0.598311, 0.130528, 0],
    [0.578556, 0.238423, 0],
    [0.547158, 0.343077, 0],
    [0.504649, 0.443762, 0],
    [0.451556, 0.53975, 0],
    [0.358229, 0.636924, 0],
    [0.2484, 0.707276, 0],
    [0.127259, 0.750044, 0],
    [0, 0.76447, 0],
    [-0.127259, 0.750044, 0],
    [-0.2484, 0.707276, 0],
    [-0.358229, 0.636924, 0],
    [-0.451556, 0.53975, 0],
    [-0.504797, 0.443762, 0],
    [-0.547291, 0.343077, 0],
    [-0.578605, 0.238423, 0],
    [-0.598311, 0.130528, 0],
    [-0.648009, 0.037218, 0],
    [-0.747183, 0, 0],
    [-0.747183, -0.5, 0]
  )
    .md('GT2_2mm profile')
    .gridView(),
  diameter: (teeth) => ToothSpacing(teeth, 2, 0.254),
  toothDepth: 0.764,
  toothWidth: 1.494,
};

export const GT2_3mm = {
  profile: ToothProfileToFace(
    [-1.155171, -0.5, 0],
    [-1.155171, 0, 0],
    [-1.065317, 0.016448, 0],
    [-0.989057, 0.062001, 0],
    [-0.93297, 0.130969, 0],
    [-0.90364, 0.217664, 0],
    [-0.863705, 0.408181, 0],
    [-0.800056, 0.591388, 0],
    [-0.713587, 0.765004, 0],
    [-0.60519, 0.926747, 0],
    [-0.469751, 1.032548, 0],
    [-0.320719, 1.108119, 0],
    [-0.162625, 1.153462, 0],
    [0, 1.168577, 0],
    [0.162625, 1.153462, 0],
    [0.320719, 1.108119, 0],
    [0.469751, 1.032548, 0],
    [0.60519, 0.926747, 0],
    [0.713587, 0.765004, 0],
    [0.800056, 0.591388, 0],
    [0.863705, 0.408181, 0],
    [0.90364, 0.217664, 0],
    [0.932921, 0.130969, 0],
    [0.988924, 0.062001, 0],
    [1.065168, 0.016448, 0],
    [1.155171, 0, 0],
    [1.155171, -0.5, 0]
  )
    .md('GT2_3mm profile')
    .gridView(),
  diameter: (teeth) => ToothSpacing(teeth, 3, 0.381),
  toothDepth: 1.169,
  toothWidth: 2.31,
};

export const GT2_5mm = {
  profile: ToothProfileToFace(
    [-1.975908, -0.75, 0],
    [-1.975908, 0, 0],
    [-1.797959, 0.03212, 0],
    [-1.646634, 0.121224, 0],
    [-1.534534, 0.256431, 0],
    [-1.474258, 0.426861, 0],
    [-1.446911, 0.570808, 0],
    [-1.411774, 0.712722, 0],
    [-1.368964, 0.852287, 0],
    [-1.318597, 0.989189, 0],
    [-1.260788, 1.123115, 0],
    [-1.195654, 1.25375, 0],
    [-1.12331, 1.380781, 0],
    [-1.043869, 1.503892, 0],
    [-0.935264, 1.612278, 0],
    [-0.817959, 1.706414, 0],
    [-0.693181, 1.786237, 0],
    [-0.562151, 1.851687, 0],
    [-0.426095, 1.9027, 0],
    [-0.286235, 1.939214, 0],
    [-0.143795, 1.961168, 0],
    [0, 1.9685, 0],
    [0.143796, 1.961168, 0],
    [0.286235, 1.939214, 0],
    [0.426095, 1.9027, 0],
    [0.562151, 1.851687, 0],
    [0.693181, 1.786237, 0],
    [0.817959, 1.706414, 0],
    [0.935263, 1.612278, 0],
    [1.043869, 1.503892, 0],
    [1.123207, 1.380781, 0],
    [1.195509, 1.25375, 0],
    [1.26065, 1.123115, 0],
    [1.318507, 0.989189, 0],
    [1.368956, 0.852287, 0],
    [1.411872, 0.712722, 0],
    [1.447132, 0.570808, 0],
    [1.474611, 0.426861, 0],
    [1.534583, 0.256431, 0],
    [1.646678, 0.121223, 0],
    [1.798064, 0.03212, 0],
    [1.975908, 0, 0],
    [1.975908, -0.75, 0]
  )
    .md('GT2_5mm profile')
    .gridView(),
  diameter: (teeth) => ToothSpacing(teeth, 5, 0.5715),
  toothDepth: 1.969,
  toothWidth: 3.952,
};

export const Pulley = (profile, teeth) => {
  const pulley_OD = profile.diameter(teeth);
  const tooth_depth = profile.toothDepth;
  const tooth_width = profile.toothWidth;
  const toothDistanceFromCentre = Math.sqrt(
    Math.pow(pulley_OD / 2, 2) -
      Math.pow((tooth_width + additionalToothWidth) / 2, 2)
  );
  const toothWidthScale = (tooth_width + additionalToothWidth) / tooth_width;
  const toothDepthScale = (tooth_depth + additionalToothDepth) / tooth_depth;
  var toothProfile = profile.profile;

  console.log('pulley_OD: %f', pulley_OD);
  console.log(profile);

  const center = Arc(pulley_OD, pulley_OD);

  //teeth - cut out of shaft

  //Scale tooth up
  toothProfile = toothProfile.scale(toothWidthScale, toothDepthScale);
  //Translate it out to where it should be
  toothProfile = toothProfile.move(0, -toothDistanceFromCentre, 0);

  var teethArray = [];
  for (let i = 0; i < teeth; i++) {
    teethArray.push(toothProfile.rz(i / teeth));
  }
  const teethToCut = Group(...teethArray);

  return center.cut(teethToCut).clean();
};

md`
# Supported belt profiles:

'''js
Pulley(MXL, 20).md('MXL').view();

Pulley(DP40, 20).md('DP40').view();

Pulley(XL, 20).md('XL').view();

Pulley(H, 20).md('H').view();

Pulley(T2_5, 20).md('T2 5mm').view();

Pulley(T5, 20).md('T5').view();

Pulley(T10, 20).md('T10').view();

Pulley(AT5, 20).md('AT 5mm').view();

Pulley(HTD_3mm, 20).md('HTD 3mm').view();

Pulley(HTD_5mm, 20).md('HTD 5mm').view();

Pulley(GT2_5mm, 20).md('GT2 5mm').view();

Pulley(GT2_5mm, 20).md('GT2 5mm').view();

Pulley(HTD_8mm, 20).md('HTD 8mm').view();

Pulley(GT2_2mm, 20).md('GT2 2mm').view();

Pulley(GT2_3mm, 20).md('GT2 3mm').view();

Pulley(GT2_5mm, 20).md('GT2 5mm').view();
'''
`;
