export const bodyDiameter = 28;
export const bodyHeight = 19;
export const bodyPlay = 0.1;
export const totalDiameter = 42;
export const tabDiameter = 7;
export const tabThickness = 1;
export const holeDiameter = 4;
export const shaftDiameter = 5;
export const shaftFlats = 3;
export const shaftFlatsLength = 6;
export const shaftOffset = 6;
export const shaftBaseDiameter = 9;
export const shaftBaseHeight = 2;
export const shaftLength = 10;
export const shaftPlay = 0.2;
export const connectorWidth = 15;
export const connectorLength = 7;
export const connectorBaseWidth = 17;
export const connectorBaseHeight = 4;
export const connectorHeight = 5;
export const reelDiameter = 20;
export const reelThickness = 4;

export const stepperMotor28byj48 = Group(
  Arc(bodyDiameter)
    .add(Box(connectorLength, connectorWidth).x(bodyDiameter / -2))
    .add(Box(connectorBaseHeight, connectorBaseWidth).x(bodyDiameter / -2 + 2))
    .ez(-bodyHeight)
    .mask(grow(bodyPlay))
    .as('body'),
  Group(
    Arc(shaftBaseDiameter).ez(0, -shaftBaseHeight),
    Arc(shaftDiameter).ez(shaftLength - shaftFlatsLength),
    Arc(shaftDiameter)
      .clip(Box(shaftDiameter, shaftFlats))
      .ez(shaftLength, shaftLength - shaftFlatsLength)
  )
    .mask(grow(shaftPlay))
    .as('shaft')
    .x(bodyDiameter / 2 - shaftOffset)
    .z(shaftBaseHeight),
  Arc(tabDiameter)
    .y(totalDiameter / 2 - tabDiameter / 2)
    .rz(0, 1 / 2)
    .hull(noOp())
    .ez(-tabThickness)
    .fitTo(
      Arc(holeDiameter)
        .ez(-tabThickness)
        .void()
        .as('hole')
        .y(totalDiameter / 2 - tabDiameter / 2)
        .rz(0, 1 / 2)
    )
).view(rz(1 / 4));
md`![28BYJ-48 Stepper Motor](https://cdn-reichelt.de/bilder/web/artikel_ws/A300/ME071_01.jpg)`;
